spring:
  # Configuración de la bd bb
  datasource:
    url: jdbc:h2:mem:bestiaryDB
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true